services:
  app:
    build: .
    container_name: "carteirinhas-app"
    command: npm run dev
    working_dir: /app
    env_file:
      - .env
    ports:
      - "5173:5173"
    volumes:
      - .:/app